---
image: python:3.9.1-buster

stages:
  - testing
  - building
  - publishing

code quality:
  stage: testing
  script:
    - make pip-install-development
    - make isort
    - make mypy
    - make coverage

build images:
  image: docker/compose:1.28.0
  services:
    - docker:18.09.7-dind
  stage: building
  variables:
    DJANGO_SETTINGS_MODULE: readable.settings.development
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker-compose build --compress --force-rm --pull
    - docker-compose push
  only:
    - master

deployment:
  image:
    name: docker/compose:1.28.0
    entrypoint:
      - /bin/sh
      - -c
  stage: publishing
  variables:
    DOCKER_TLS_VERIFY: 1
    DJANGO_SETTINGS_MODULE: readable.settings.production
  script: deployment/docker-publishing
  environment:
    name: production
    url: https://readable.pw
  only:
    - master

pages:
  stage: publishing
  script:
    - make pip-install-development
    - make coverage-html
  environment:
    name: coverage
    url: https://coverage.readable.pw
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
