repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: end-of-file-fixer
        verbose: on
      - id: trailing-whitespace
        verbose: on
  - repo: local
    hooks:
      - id: isort
        name: Trying to check correct ordering of imports
        entry: isort
        language: python
        types:
          - python
        args:
          - --check-only
        require_serial: on
        verbose: on
  - repo: local
    hooks:
      - id: mypy
        name: Running the static type checker
        entry: mypy
        language: python
        types:
          - python
        args:
          - --ignore-missing-imports
          - --follow-imports
          - silent
          - --show-column-numbers
        require_serial: on
        verbose: on
