---
version: "3.7"

x-default: &default-settings
  restart: unless-stopped
  sysctls:
    net.core.somaxconn: 65535
  ulimits:
    nofile: 65535 # file descriptors number limit
    nproc: 65535 # processes number limit

services:
  postgresql:
    <<: *default-settings
    image: postgres:13.1-alpine
    user: postgres:postgres
    environment:
      # PostgreSQL environment variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - type: volume
        source: datafiles
        target: /var/lib/postgresql/data

  readable:
    <<: *default-settings
    build: .
    image: $CI_REGISTRY/$CI_PROJECT_PATH/readable:latest
    user: nobody:nogroup
    environment:
      # PostgreSQL environment variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      # Django environment variables:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
    tmpfs:
      - /tmp
    volumes:
      - type: volume
        source: mediafiles
        target: /application/readable/resources/mediafiles
      - type: volume
        source: staticfiles
        target: /application/readable/resources/staticfiles
    depends_on:
      - postgresql

  nginx:
    <<: *default-settings
    build: ./deployment/nginx
    image: $CI_REGISTRY/$CI_PROJECT_PATH/nginx:latest
    tmpfs:
      - /tmp/readable_cache
      - /var/cache/nginx
    volumes:
      - type: volume
        source: mediafiles
        target: /application/readable/resources/mediafiles
      - type: volume
        source: staticfiles
        target: /application/readable/resources/staticfiles
    depends_on:
      - readable
    scale: 4
    ports:
      - 8080-8083:80/tcp

volumes:
  datafiles:
    driver: local
  mediafiles:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  staticfiles:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    driver: bridge
