---
version: "3.7"

x-default: &default-settings
  restart: unless-stopped
  sysctls:
    net.core.somaxconn: 65535
  ulimits:
    nofile: 65535
    nproc: 65535

services:
  postgresql:
    <<: *default-settings
    image: postgres:13.2-alpine
    container_name: postgresql
    user: postgres:postgres
    environment:
      # PostgreSQL environment variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - type: volume
        source: datafiles
        target: /var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

  readable:
    <<: *default-settings
    build: .
    image: $CI_REGISTRY/$CI_PROJECT_PATH/readable:latest
    container_name: readable
    user: nobody:nogroup
    environment:
      # PostgreSQL environment variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      # Django environment variables:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
    tmpfs:
      - /tmp
    volumes:
      - type: volume
        source: mediafiles
        target: /application/readable/resources/mediafiles
      - type: volume
        source: staticfiles
        target: /application/readable/resources/staticfiles
    depends_on:
      - postgresql
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
      - target: 8001
        published: 8001
        protocol: tcp
        mode: host
      - target: 8002
        published: 8002
        protocol: tcp
        mode: host
      - target: 8003
        published: 8003
        protocol: tcp
        mode: host

volumes:
  datafiles:
    driver: local
  mediafiles:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  staticfiles:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    driver: bridge
