version: "3.6"

x-default: &default-settings
  restart: always
  sysctls:
    net.core.somaxconn: 65535
  ulimits:
    nproc: 65535
    nofile:
      soft: 32767
      hard: 65535

services:
  redis:
    <<: *default-settings
    image: redis:6.0-alpine
    tmpfs:
      - /data
      - /tmp

  postgresql:
    <<: *default-settings
    image: postgres:13.0-alpine
    environment:
      # PostgreSQL environment variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - type: volume
        source: datafiles
        target: /var/lib/postgresql/data

  readable:
    <<: *default-settings
    build: .
    image: $CI_REGISTRY/$CI_PROJECT_PATH/readable:latest
    environment:
      # PostgreSQL environment variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      # Django environment variables:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
    volumes:
      - type: volume
        source: mediafiles
        target: /application/readable/resources/mediafiles
        volume:
          nocopy: true
      - type: volume
        source: staticfiles
        target: /application/readable/resources/staticfiles
        volume:
          nocopy: true
    depends_on:
      - redis
      - postgresql

  nginx:
    <<: *default-settings
    build: ./deployment/nginx
    image: $CI_REGISTRY/$CI_PROJECT_PATH/nginx:latest
    volumes:
      - type: volume
        source: mediafiles
        target: /application/readable/resources/mediafiles
        volume:
          nocopy: true
      - type: volume
        source: staticfiles
        target: /application/readable/resources/staticfiles
        volume:
          nocopy: true
    depends_on:
      - readable
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host

volumes:
  datafiles:
    driver: local
  mediafiles:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  staticfiles:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    driver: bridge
