[tool.poetry]
name        = "readable"
version     = "0.1.2"
authors     = ["Andrew Malchuk <andrew.malchuk@yandex.ru>"]
description = "Check and improve the spelling and grammar of documents"
keywords    = ["readability", "text statistics", "spelling", "grammar", "overall score"]
homepage    = "https://readable.pw"
repository  = "https://gitlab.com/amalchuk/readable"
readme      = "README.md"
license     = "MIT"
include     = ["manage.py"]

[tool.poetry.dependencies]
python       = "3.9.0"
django       = "3.1.2"
pymupdf      = "1.18.1"
python-docx  = "0.8.10"
scienco      = "0.2.1"
simplethread = "0.1.2"
django-redis = { version = "4.12.1", platform = "linux", optional = true }
psycopg2     = { version = "2.8.6", platform = "linux", optional = true }
uwsgi        = { version = "*", platform = "linux", optional = true }

[tool.poetry.extras]
deployment = ["django-redis", "psycopg2", "uwsgi"]

[tool.poetry.dev-dependencies]
coverage       = { version = "^5.3", allow-prereleases = true, extras = ["toml"]}
isort          = { version = "^5.6", allow-prereleases = true }
pre-commit     = { version = "^2.7", allow-prereleases = true }
docker-compose = { version = "*", allow-prereleases = true }
mypy           = { version = "*", allow-prereleases = true }

[tool.coverage.run]
branch = true
omit   = [
    "readable/migrations/0001_initial.py",
    "readable/settings/common.py",
    "readable/settings/development.py",
    "readable/settings/production.py",
    "readable/settings/staging.py",
    "readable/wsgi.py"
]
source = ["readable"]

[tool.coverage.report]
precision  = 2
skip_empty = true

[tool.isort]
force_single_line          = true
force_sort_within_sections = true
known_third_party          = ["django", "docx", "fitz", "scienco", "simplethread"]
lexicographical            = true
single_line_exclusions     = ["typing"]
