[tool.poetry]
name        = "readable"
version     = "0.1.3"
authors     = ["Andrew Malchuk <andrew.malchuk@yandex.ru>"]
description = "Check and improve the spelling and grammar of documents"
keywords    = ["readability", "text statistics", "spelling", "grammar", "overall score"]
homepage    = "https://readable.pw"
repository  = "https://gitlab.com/amalchuk/readable"
readme      = "README.md"
license     = "MIT"
include     = ["manage.py"]

[tool.poetry.dependencies]
python       = "3.8.5"
django       = "3.1"
pymupdf      = "1.17.5"
python-docx  = "0.8.10"
django-redis = { version = "4.12.1", platform = "linux", optional = true }
psycopg2     = { version = "2.8.5", platform = "linux", optional = true }
uwsgi        = { version = "*", platform = "linux", optional = true }

[tool.poetry.extras]
deployment = ["django-redis", "psycopg2", "uwsgi"]

[tool.poetry.dev-dependencies]
docker-compose  = ">=1.26"
git-filter-repo = ">=2.28"
pre-commit      = ">=2.6"
pylint          = ">=2.5.3, <3.0"
coverage        = { version = ">=5.2", extras = ["toml"]}
isort           = { version = ">=4.3.5, <5.0", extras = ["pyproject"]}
mypy            = { version = "*", allow-prereleases = true }

[tool.isort]
combine_as_imports = true
combine_star       = true
known_third_party  = ["django", "docx", "fitz"]
line_length        = 125
multi_line_output  = 2

[tool.coverage.run]
branch = true
omit   = [
    "readable/migrations/0001_initial.py",
    "readable/settings/common.py",
    "readable/settings/development.py",
    "readable/settings/production.py",
    "readable/settings/staging.py",
    "readable/wsgi.py"
]
source = ["readable"]

[tool.coverage.report]
precision    = 2
skip_covered = true

[tool.coverage.html]
directory = "public"

[build-system]
requires = ["pip", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"
