[tool.poetry]
name        = "readable"
version     = "0.2.5"
authors     = ["Andrew Malchuk <andrew.malchuk@yandex.ru>"]
description = "Check and improve the spelling and grammar of documents"
keywords    = ["readability", "text statistics", "spelling", "grammar", "overall score"]
homepage    = "https://readable.pw"
repository  = "https://gitlab.com/amalchuk/readable"
readme      = "README.md"
license     = "MIT"
include     = ["manage.py"]

[tool.poetry.dependencies]
python              = ">=3.9, <4.0"
diskcache           = "5.1.0"
django              = "3.1.4"
djangorestframework = "3.12.2"
pymupdf             = "1.18.4"
python-docx         = "0.8.10"
scienco             = { version = "*", allow-prereleases = true }
simplethread        = { version = "*", allow-prereleases = true }
psycopg2            = { version = "*", allow-prereleases = true, optional = true }
uwsgi               = { version = "*", allow-prereleases = true, optional = true }

[tool.poetry.extras]
deployment = ["psycopg2", "uwsgi"]

[tool.poetry.dev-dependencies]
docker-compose = "^1.27"
isort          = "^5.6"
reportlab      = "^3.5"
coverage       = { version = "^5.3", extras = ["toml"]}
mypy           = { version = "*", allow-prereleases = true }

[tool.coverage.run]
branch = true
omit   = [
    "readable/migrations/0001_initial.py",
    "readable/settings/common.py",
    "readable/settings/development.py",
    "readable/settings/production.py",
    "readable/settings/staging.py",
    "readable/wsgi.py"
]
source = ["readable"]

[tool.coverage.report]
precision  = 2
skip_empty = true

[tool.isort]
force_single_line          = true
force_sort_within_sections = true
known_third_party          = [
    "django",
    "docx",
    "fitz",
    "rest_framework",
    "scienco",
    "simplethread"
]
lexicographical            = true
line_length                = 125
single_line_exclusions     = ["typing"]
