#!/usr/bin/env bash

# Exit immediately if a pipeline returns a non-zero status:
set -e

if [ "$1" == "uwsgi" ]; then
  for subcommand in collectstatic migrate; do
    python manage.py $subcommand --no-input >> /dev/null
  done
fi

exec "$@"
