#!/usr/bin/env bash

# Exit immediately if a pipeline returns a non-zero status:
set -e

if [ "$1" == "uwsgi" ]; then
  # Collecting the static files in a single location:
  python manage.py collectstatic \
    --no-input \
    --clear >> /dev/null

  # Updating the database schema:
  python manage.py migrate \
    --no-input >> /dev/null
fi

exec "$@"
